### PR TITLE
Passing in input and output directories as arguments to script

### PR DESCRIPTION
**Pull request by matt-graham**
Hi @uclrmhigid - just suggesting a couple of changes to your job script and Python script here that I noticed while responding to email. 

One thing to note is to be careful about [including spaces in filenames](https://swcarpentry.github.io/shell-novice/03-create.html#good-names-for-files-and-directories) as spaces are typically used to separate command line arguments so the line
```
python $PROJECT_DIR/Python script 20062024.py --data-dir $PROJECT_DIR/data --output-dir outputs
```
in your job script would be interpreted as run `python` on the file `$PROJECT_DIR/Python` (`$PROJECT_DIR` is a variable that will be replaced with the value defined earlier in the job script here) with six separate arguments `script`, `20062024.py`, `--data-dir`, `$PROJECT_DIR/data`, `--output-dir` and `outputs`. To avoid this you can enclose the filename in quotation marks
```
python "$PROJECT_DIR/Python script 20062024.py" --data-dir $PROJECT_DIR/data --output-dir outputs
```
however to avoid having to remember to do this I would recommend using underscores instead of spaces as a word separator in filenames. Also by having files under version control as you do here via Git, you can avoid needing to track different versions of files manually by including dates etc. in the file name, as if you make changes to files here and commit these, you can always still go back to the version of the files at a previous date easily, so I've also recommended here removing the date part of the filename.

In the actual Python script, I've transported over the logic for parsing command line arguments from the example, and used these to replace the hard-coded paths in your script. For this to work as expected you would need to have a `data` subdirectory inside your  `/home/rmhigid/Scratch/Lung-ORACLE` which contains the relevant data file (`clusterfile_20062024.csv`). The `joblib` dump of the model saved in the script would be written to a directory `outputs_<job_id>` in the `/home/rmhigid/Scratch/Lung-ORACLE` directory.

### CODE REVIEW

**Comment by matt-graham** [comment]
In the job script you will probably also want to adjust the resources requested in the lines

```
# Request 1 minutes of wallclock time (format hours:minutes:seconds).
#$ -l h_rt=0:1:0
# Request 1 gigabyte of RAM for each core/thread 
# (must be an integer followed by M, G, or T)
#$ -l mem=1G
# Request 1 gigabyte of TMPDIR space (default is 10 GB)
#$ -l tmpfs=1G
# Set the name of the job.
#$ -N python-analysis-example
# Request 1 cores.
#$ -pe smp 1
```

to something more substantial - particularly the time and memory requested (note the latter is per-core so if you for example request 4 cores and 8GB memory per core, you will have 32GB memory available in total.

**Review by uclrmhigid — APPROVED** [review]
Thanks so much!

**Review by uclrmhigid — APPROVED** [review]

**Comment by uclrmhigid** [comment]
Hi Matt

Thanks so much for all your help

Apologies, I am still having issues.  Largely in terms of transferring data/outputs.

Transferring data....
From myriad to home computer
I tried the following code adapted from what you kindly suggested

(venv) ***@***.*** myriad-python-analysis-example]$ scp -o ***@***.*** ***@***.***:~/Scratch/myriad-python-analysis-example/outputs_465456/inflammation-05-plot.pdf C:/Users/olarg/OneDrive/Desktop

And I got the following output:
 ------------------------------------------------------------------------
 Information Systems - Information Services Division - UCL

 Access to and use of this system are restricted to authorised individuals
 and subject to UCL Computing Regulations.
 ------------------------------------------------------------------------

Password:
Password:
Loading default-modules/2018
  Loading requirement: gcc-libs/4.9.2 cmake/3.21.1 flex/2.5.39 git/2.32.0 apr/1.7.0 apr-util/1.6.1 subversion/1.14.1
    screen/4.9.0 gerun nano/2.4.2 nedit/5.6-aug15 dos2unix/7.3 giflib/5.1.1 emacs/28.1 tmux/3.3a mrxvt/0.5.4
    userscripts/1.4.0 rcps-core/1.0.0 compilers/intel/2018/update3 mpi/intel/2018/update3/intel
ssh: Could not resolve hostname c: Name or service not known
lost connection
Connection to myriad.rc.ucl.ac.uk closed.
Killed by signal 1.

From RDSS to myriad
I checked my emails from RDSS, and you're right, the location of my storage area is: /mnt/gpfs/live/rd01__/ritd-ag-project-rd01fz-rgidd68/

I'm not sure what I expected to happen, but when I run

scp ssh.rd.ucl.ac.uk:/mnt/gpfs/live/rd01__/ritd-ag-project-rd01fz-rgidd68/Python/Synthetic/

I get the following response:
usage: scp [-12346BCpqrv] [-c cipher] [-F ssh_config] [-i identity_file]
           [-l limit] [-o ssh_option] [-P port] [-S program]
           [[user@]host1:]file1 ... [[user@]host2:]file2

When I then run ls I don't see the data 'clusterfile_20062024.csv' from within the Synthetic folder listed? I don't know if it has been uploaded somewhere?
[cid:e0b8c7f5-af26-428e-ab34-374b31f443ba]
I know I need to save it within a folder named Data, I'm not 100% sure how to go about that either! I'm connected to the VPN

Updating the job script and python code
Thanks so much for the suggested changes to the code.  Tbh, the pull requests and commits were new to me, and I think I messed it up a little at first, but all resolved now!

Not sure if the above makes any sense!

Thanks again for all your help

BW
Rebecca
________________________________
From: Matt Graham ***@***.***>
Sent: 21 June 2024 12:02
To: uclrmhigid/Lung-ORACLE ***@***.***>
Cc: Giddings, Rebecca ***@***.***>; Mention ***@***.***>
Subject: [uclrmhigid/Lung-ORACLE] Passing in input and output directories as arguments to script (PR #1)


⚠ Caution: External sender


Hi @uclrmhigid<https://github.com/uclrmhigid> - just suggesting a couple of changes to your job script and Python script here that I noticed while responding to email.

One thing to note is to be careful about including spaces in filenames<https://swcarpentry.github.io/shell-novice/03-create.html#good-names-for-files-and-directories> as spaces are typically used to separate command line arguments so the line

python $PROJECT_DIR/Python script 20062024.py --data-dir $PROJECT_DIR/data --output-dir outputs


in your job script would be interpreted as run python on the file $PROJECT_DIR/Python ($PROJECT_DIR is a variable that will be replaced with the value defined earlier in the job script here) with six separate arguments script, 20062024.py, --data-dir, $PROJECT_DIR/data, --output-dir and outputs. To avoid this you can enclose the filename in quotation marks

python "$PROJECT_DIR/Python script 20062024.py" --data-dir $PROJECT_DIR/data --output-dir outputs


however to avoid having to remember to do this I would recommend using underscores instead of spaces as a word separator in filenames. Also by having files under version control as you do here via Git, you can avoid needing to track different versions of files manually by including dates etc. in the file name, as if you make changes to files here and commit these, you can always still go back to the version of the files at a previous date easily, so I've also recommended here removing the date part of the filename.

In the actual Python script, I've transported over the logic for parsing command line arguments from the example, and used these to replace the hard-coded paths in your script. For this to work as expected you would need to have a data subdirectory inside your /home/rmhigid/Scratch/Lung-ORACLE which contains the relevant data file (clusterfile_20062024.csv). The joblib dump of the model saved in the script would be written to a directory outputs_<job_id> in the /home/rmhigid/Scratch/Lung-ORACLE directory.

________________________________
You can view, comment on, or merge this pull request online at:

  https://github.com/uclrmhigid/Lung-ORACLE/pull/1

Commit Summary

  *   9f3c968<https://github.com/uclrmhigid/Lung-ORACLE/pull/1/commits/9f3c96836ba41c2e62d50ce69a8a72e417a45f7d> Passing in input and output directories as arguments to script

File Changes

(2 files<https://github.com/uclrmhigid/Lung-ORACLE/pull/1/files>)

  *   R python_script.py<https://github.com/uclrmhigid/Lung-ORACLE/pull/1/files#diff-39568ea777228a6a7eaa8bd3234916e01d048a402aa718069a9a2143f136328c> (12)
  *   M run_analysis.sh<https://github.com/uclrmhigid/Lung-ORACLE/pull/1/files#diff-2dc7e30c4e2b8572033845729b2491d161673d7545fcb360db23ebcb2b39b48b> (2)

Patch Links:

  *   https://github.com/uclrmhigid/Lung-ORACLE/pull/1.patch
  *   https://github.com/uclrmhigid/Lung-ORACLE/pull/1.diff

**Comment by matt-graham** [comment]
Hi @uclrmhigid 

The error 

> ssh: Could not resolve hostname c: Name or service not known

is as in the command

```
scp -o ***@***.*** ***@***.***:~/Scratch/myriad-python-analysis-example/outputs_465456/inflammation-05-plot.pdf C:/Users/olarg/OneDrive/Desktop
```

the destination argument to `scp` that is `C:/Users/olarg/OneDrive/Desktop` is being interpreted as accessing the path `/Users/olarg/OneDrive/Desktop` on an SSH host `C`, as colons are used to separate host names and paths in the source and destination arguments to `scp`. This is partly due to differing conventions our how file paths are structured on Windows and Unix-like (POSIX) systems. On Unix-like systems there is no initial 'drive' specifier before a colon and paths always use the forward slash `/` as path separator. 

How to resolve depends a bit on what terminal interface you are executing the above `scp` command on Windows on:
- If using `scp` from the built-in CMD prompt or PowerShell terminals then you should change the destination `C:/Users/olarg/OneDrive/Desktop` to `C:\Users\olarg\OneDrive\Desktop` (using backslashes rather than forward slashes should make the command recognise this is meant to be a Windows path rather than a host name and Unix path)
- If using a MINGW64 terminal emulator like Git Bash, that provides a Unix like environment on Windows, then you should change the destination `C:/Users/olarg/OneDrive/Desktop` to `/c/Users/olarg/OneDrive/Desktop`
- If using Cygwin, another terminal emulator providing a Unix like environment on Windows, then you should change the destination `C:/Users/olarg/OneDrive/Desktop` to `/cygdrive/c/Users/olarg/OneDrive/Desktop`
-In a MINGW64 terminal like Git bash.

---

The message

```
usage: scp [-12346BCpqrv] [-c cipher] [-F ssh_config] [-i identity_file]
           [-l limit] [-o ssh_option] [-P port] [-S program]
           [[user@]host1:]file1 ... [[user@]host2:]file2
```

when you run

```
scp ssh.rd.ucl.ac.uk:/mnt/gpfs/live/rd01__/ritd-ag-project-rd01fz-rgidd68/Python/Synthetic/
```

is because you are missing the second destination argument. Generally commands will print usage messages when you don't provide arguments in the expected format / number. I think in the original template command I sent you the destination was `.` which is a shorthand for the current working directory which was probably easy to miss. Just adding a `.` as the second argument to the command above should make it work (with a space separating from previous argument) or you could use another path on Myriad - for example `~/Scratch` would transfer to the root of your scratch space.

**Comment by uclrmhigid** [comment]
Thanks so much (again) Matt

I have sorted getting data from RDSS to myriad 🙂 with your help

I've just ran my first job from my github.  Unfortunately I got the following error
[cid:f46168cf-2ea2-4149-a9b3-a7224893eb55]

which seems to relate to the following bit of the code
[cid:e715bb4d-d693-43fb-9539-3701a5f0d16d]

Apologies, should I be amending this section of code to include the Path of where I want this saved to?

Sorry if I'm misunderstanding

Thanks again

BW
Rebecca
________________________________

**Comment by matt-graham** [comment]
> Unfortunately I got the following error [cid:f46168cf-2ea2-4149-a9b3-a7224893eb55] which seems to relate to the following bit of the code [cid:e715bb4d-d693-43fb-9539-3701a5f0d16d]

I think GitHub isn't able to show images you have attached in an email reply here? Sorry I didn't spot initially you were replying to this via email rather than directly on pull request (https://github.com/uclrmhigid/Lung-ORACLE/pull/1), possibly best we continue conversation over email, so if you can forward me last message you sent I'll reply over email.

**Pull request merged**
